<a href="https://colab.research.google.com/github/BMClab/BasesComputacionais/blob/master/FOSS/conjuntos.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

#Projeto final da disciplina Bases Computacionais da Ciência

####Marcos Duarte

Universidade Federal do ABC

Período noturno

Campos de São Bernardo do Campo, Brasil

Integrantes:
####Alice Vieira Garcia 
####Lucas Amorim Leal 

#Conteúdo

*   Conjuntos Numéricos
*   Representação de conjuntos no Python
*   Operações com conjuntos usando métodos numéricos
*   União
*   Interseção 
*   Diferença de conjuntos
*   Diferença Simétrica
*   Pertinência
*   Referências


#Conjuntos Numéricos 


Serão agrupados neste repositório soluções para problemas em que são empregadas operações com conjuntos. 

#Representação de conjuntos no Python
Temos dois métodos de representarmos um conjunto de numeros em python.

1)

In [ ]:
A = {1, 2, 3, 4, 5}
print(A)

{1, 2, 3, 4, 5}


2) Pela biblioteca numpy

In [ ]:
import numpy as np

B = np.array([1, 2, 3, 4, 5, 6])
print(B)

C = np.arange(0, 11, 2)
print(C)

D = np.linspace(1, 5, 5)
print(D)

[1 2 3 4 5 6]
[ 0  2  4  6  8 10]
[1. 2. 3. 4. 5.]


#Operações com conjuntos usando métodos numéricos como: 



*   União
*   Interseção 
*   Diferença de conjuntos
*   Diferença simétrica
*   Pertinência 








#Os métodos 


#União



A união de conjuntos corresponde a junção dos elementos dos conjuntos dados, ou seja, é o conjunto formado pelos elementos de um conjunto mais os elementos dos outros conjuntos.

Se existirem elementos que se repetem nos conjuntos, ele aparecerá uma única vez no conjunto união.

Para representar a união usamos o símbolo U.

<figure><center><img src="https://static.todamateria.com.br/upload/un/ia/uniao.jpg" width=300 alt="União"/></center></figure> 

Suponha que tenhamos dois conjuntos E = {0,1,3,5,7,9} e F = {0,2,4,6,8} e desejamos construir um conjunto C que é a união dos conjuntos A e B. Matematicamente, temos que G = A∪B = {0,1,2,3,4,5,6,7,8,9}. Note que o 0 aparece em ambos conjuntos, mas aparece uma única vez no conjunto G.

Em Python, podemos realizar a operação acima da seguinte forma:



In [ ]:
E = {1, 3, 5, 7, 9} 
F = {0, 2, 4, 6, 8}
G = E.union(F)
print(G)

{0, 1, 2, 3, 4, 5, 6, 7, 8, 9}


Modo alternativo de executar a união de dois conjuntos:

In [ ]:
H = E | F
print(H)

{0, 1, 2, 3, 4, 5, 6, 7, 8, 9}


#Interseção 

A intersecção de conjuntos corresponde aos elementos que se repetem nos conjuntos dados. Ela é representada pelo símbolo ∩.

<figure><center><img src="https://static.todamateria.com.br/upload/in/te/interseca_ao.jpg?auto_optimize=low" width=300 alt="Intersecção"/></center></figure> 



Em Python, podemos realizar a operação acima da seguinte forma:



In [ ]:
I = {0, 1, 3, 4, 5, 7, 9}
J = {0, 2, 4, 6, 8}
K = I.intersection(J)
print(K)

{0, 4}


Modo alternativo de executar a Interseção de dois conjuntos:

In [ ]:
L = I & J
print(L)

{0, 4}


#Diferença de conjuntos 

A diferença de conjuntos é representada pelos elementos de um conjunto que não aparecem no outro conjunto.

<figure><center><img src="https://e7.pngegg.com/pngimages/273/846/png-clipart-venn-diagram-set-theory-diferencia-de-conjuntos-lady-macbeth-fainting-template-angle.png" width=300 alt="Diferença de Conjuntos"/></center></figure> 


Em Python, podemos realizar a operação acima da seguinte forma:


In [ ]:

M = {1, 2, 3, 4}
N = {3, 4, 5, 6}
O = M.difference(N)
P = N.difference(M)
print(O)
print(P)
     

{1, 2}
{5, 6}


Modo alternativo de executar a diferença de dois conjuntos:

In [ ]:
Q = M - N
R = N - M
print(Q)
print(R)

{1, 2}
{5, 6}


#Diferença Simétrica 

A diferença simétrica entre os conjuntos A e B é o conjunto de todos os elementos que pertencem à reunião dos conjuntos A e B e não pertencem à interseção dos conjuntos A e B.

<figure><center><img src="https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcS-D5FM1SHPub3kcWlQ1H6cx1d5vKA1lxa0Wg&usqp=CAU" width=300 alt="Diferença Sinétrica"/></center></figure> 


Em Python, podemos realizar a operação acima da seguinte forma:

In [ ]:
S = {14, 16, 21, 23}
T = {23, 21, 52, 64}
print(S.symmetric_difference(T))

{64, 14, 16, 52}


#Pertinência 

Além das operações tradicionais de união, interseção e diferença, também temos operações de verificação de pertinência. Para verificar se um determinado elemento pertence a um conjunto, podemos usar o já conhecido operador de pertinência in:




In [ ]:

print(14 in A)
print(6 in C)
print(9 in G)
print(3 in I)
print(2 in K)
print(21 in M)

False
True
True
True
False
False


Também podemos verificar se um conjunto é um subconjunto de outro:

a = {1, 2, 3, 4}
c = {1, 2}
c.issubset(a)
True
a.issubset(c)
False

In [ ]:
U = {1, 2, 3, 4}
V = {1, 2}
W = U.issubset(V)
X = V.issubset(U)
print(W)
print(X)

False
True


#Referências 

*   https://algoritmosempython.com.br/cursos/programacao-python/conjuntos/
*   https://pythonhelp.wordpress.com/2013/06/18/conjuntos-em-python/ 
*   https://www.todamateria.com.br/teoria-dos-conjuntos/